repos:
  # black
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  # flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
  # isort
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        language_version: python3.12
  # pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml # Attempt to load all toml files to verify syntax
      - id: check-yaml # Attempt to load all yaml files to verify syntax
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: end-of-file-fixer # Make sure files end in a newline and only a newline
        exclude: >
          (?x)(
            ^.*\.md$|
            ^docs/|
            ^.github/|
            ^tests/fixtures/|
            ^.*\.csv$|
            ^.*\.dat$|
            ^.*\.log$
          )
      - id: requirements-txt-fixer # Sort entries in requirements.txt and remove incorrect entry for pkg-resources==0.0.0
      - id: trailing-whitespace # Trim trailing whitespace
        exclude: >
          (?x)(
            ^.*\.md$|
            ^docs/|
            ^.github/|
            ^tests/fixtures/|
            ^.*\.csv$|
            ^.*\.dat$|
            ^.*\.log$
          )
